using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using OpenConstructionSet.Installations;
using OpenConstructionSet.Mods.Context;

namespace OCSPatchers.Patchers
{
    internal class OCSPatcherGeneral : OCSPatcherBase
    {
        public override string PatcherName => "Generalpatcher";

        public override string[] ExcludedModNames => new string[]
        {
            "Bigger Backpacks",
            "-KCF autogenerated patch-",
        };

        public override Task ApplyPatch(IModContext context, IInstallation installation)
        {
            return Task.CompletedTask;
        }
    }
}
